export enum OrderStatus {
  PENDING = 'PENDING',
  AWAITING_PROCESSING = 'AWAITING PROCESSING',
  PROCESSING = 'PROCESSING',
  READY_TO_SHIP = 'READY TO SHIP',
  SHIPPED = 'SHIPPED',
  CANCELLED = 'CANCELLED',
  DECLINED = 'DECLINED',
  REFUNDED = 'REFUNDED',
}
