version: '3.7'

services: 
    uzuri-shopper-stg:
        image: registry.gitlab.com/uzuri/uzuri-web/staging:latest
        container_name: uzuri-shopper-stg
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports: 
            - 8022:3000
        restart: always