export const GOOGLE_ANALYTICS_TRACKING_ID = 'UA-210109143-1 '
export const BASE_API_URL = `${process.env.NEXT_PUBLIC_API_HOST}/api/v1`
export const API_ROOT_URL = process.env.NEXT_PUBLIC_API_HOST
export const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT
export const CLOUDINARY_UPLOAD_URL = process.env.NEXT_PUBLIC_CLOUDINARY_API_UPLOAD_URL || ''
export const CLOUDINARY_UPLOAD_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_UPLOAD_KEY
export const CLOUDINARY_UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_API_UPLOAD_PRESET || ''
export const GEO_LOCATION_API = process.env.NEXT_PUBLIC_GEO_LOCATION_API
export const CLOUDINARY_API_UPLOAD_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_API_UPLOAD_SECRET
export const CLOUDINARY_API_UPLOAD_CLOUD_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_API_UPLOAD_CLOUD_NAME
export const ENV = process.env.NEXT_PUBLIC_NODE_ENV
export const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY || ''
export const FACEBOOK_PIXEL_ID = process.env.NEXT_PUBLIC_FACEBOOK_PIXEL_ID
